# Generated by Django 2.1.4 on 2019-03-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rpwd', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unknown', max_length=10, verbose_name='Gender')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('user', 'user'), ('Admin', 'Admin')], default='user', max_length=10, verbose_name='UserType')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blog_auth_user',
            },
        ),
    ]
