# Generated by Django 2.1.4 on 2018-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
