# Generated by Django 2.1.4 on 2018-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20181219_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(blank=True, max_length=65, null=True, unique=True),
        ),
    ]
