# Generated by Django 2.1.4 on 2018-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20181219_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(default=None, max_length=65, unique=True),
            preserve_default=False,
        ),
    ]
