# Generated by Django 2.1.4 on 2019-03-29 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, unique=True)),
                ('image', models.ImageField(upload_to='%y/%m/%d')),
                ('short_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blogapp_banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=65, unique=True)),
            ],
            options={
                'db_table': 'blogapp_category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'blogapp_contact',
            },
        ),
        migrations.CreateModel(
            name='Gal_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
            ],
            options={
                'db_table': 'blogapp_gal_image',
            },
        ),
        migrations.CreateModel(
            name='Image_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('is_image', models.BooleanField(default=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'blogapp_image_file',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=65, unique=True)),
                ('lvl', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Menu')),
            ],
            options={
                'db_table': 'blogapp_menu',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=65, unique=True)),
                ('photos', models.ManyToManyField(blank=True, to='blog.Gal_Image')),
            ],
            options={
                'db_table': 'blogapp_page',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('is_featured_news', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=65, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('photos', models.ManyToManyField(blank=True, to='blog.Gal_Image')),
            ],
            options={
                'db_table': 'blogapp_post',
            },
        ),
    ]
