from django.urls import path, re_path
from . import views

app_name = 'adminapp'
urlpatterns = [
    path('', views.login, name='login'),
    path('category/add/', views.add_category, name='add_category'),
    path('article/add/', views.add_post),
    path('article/list/', views.post_list),
    path('category/list/', views.category_list),
    path('event/list/', views.event_list),
    path('event/add/', views.add_event),
    path('page/list/', views.page_list),
    path('menu/list/', views.menu_list),
    path('banner/add/', views.add_banner),
    path('banner/list/', views.banner_list),
    re_path('banner/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_banner),
    re_path('banner/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_banner),
    re_path('category/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_category),
    re_path('article/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_post),
    re_path('category/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_category),
    re_path('event/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_event),
    re_path('article/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_post),
    re_path('article/change_state/(?P<pk>[a-zA-Z0-9_-]+)/', views.post_state),
    re_path('event/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_event),
    re_path('event/change_state/(?P<pk>[a-zA-Z0-9_-]+)/', views.event_state),
    path('admin_logout/', views.admin_logout),
    path('menu/add/', views.add_menu),
    re_path('menu/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_menu),
    re_path('menu/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_menu),
    re_path('menu/change_state/(?P<pk>[a-zA-Z0-9_-]+)/', views.menu_state),
    re_path('menu/lvl-up/(?P<pk>[a-zA-Z0-9_-]+)/', views.menu_lvl_up),
    re_path('menu/lvl-down/(?P<pk>[a-zA-Z0-9_-]+)/', views.menu_lvl_down),
    re_path('delete_gal_img/(?P<pk>[a-zA-Z0-9_-]+)/(?P<pid>[a-zA-Z0-9_-]+)',
            views.delete_gal_image),
    re_path('delete_page_imgs/(?P<pk>[a-zA-Z0-9_-]+)/(?P<pid>[a-zA-Z0-9_-]+)',
            views.delete_page_images),
    path('page/add/', views.add_page),
    re_path('page/edit/(?P<pk>[a-zA-Z0-9_-]+)/', views.edit_page),
    re_path('page/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_page),
    path("ajax/photos/upload/", views.upload_photos, name="upload_photos"),
    path("ajax/photos/recent/", views.recent_photos, name="recent_photos"),
    path('change_password/', views.change_password),
    # path("tags/list/", views.tags_list),
    # re_path('tag/delete/(?P<pk>[a-zA-Z0-9_-]+)/', views.delete_tag),
]
